version: "3.8"

services:
  db_auth:
    image: postgres:15.2-alpine
    container_name: postgres_auth
    restart: always
    env_file:
      - ./auth-service/.env.db.auth
    ports:
      - 5432:5432

  redis_auth:
    image: redis:6.2-alpine
    container_name: redis_auth
    restart: always
    ports:
      - 6379:6379

  auth_api:
    build: ./auth-service/src
    container_name: auth_api
    restart: always
    depends_on:
      - db_auth
      - redis_auth
    env_file:
      - ./auth-service/.env.debug
    ports:
      - 8010:8010

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    depends_on:
      - auth_api
      - api_gateway
    ports:
      - 80:80
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_config/site.conf:/etc/nginx/conf.d/site.conf:ro

#
#  api_gateway:
#    build: ./api_gateway/src
#    container_name: api_gateway
#    restart: always
#    depends_on:
#      - db_auth
#      - redis_auth
#    env_file:
#      - ./api_gateway/.env.debug
#    expose:
#      - 8020
#